[tools]
buf = "1.57"
go = "1.25"

[tasks.start]
description = "Runs scrollwork"
run = "go run cmd/scrollwork/main.go"

[tasks.start-secrets]
description = "Runs scrollwork with secrets from 1Password"
run = "op run --env-file=.env -- go run cmd/scrollwork/main.go"

[tasks.build]
description = "Builds scrollwork"
run = "go build -o ./bin/scrollwork cmd/scrollwork/main.go"

[tasks.docker-build]
run = "docker build . -t scrollwork:latest"

description = "Builds scrollwork docker image"
[tasks.test]
description = "Run tests"
run = "go test -count=1 ./..."

[tasks.test-secrets]
description = "Run scrollwork with secrets"
run = "op run --env-file=.env -- go run cmd/scrollwork/main.go"
